version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: tickets-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tickets-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tickets-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticketsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres-data:
